import { cva } from "class-variance-authority";

export const textVariants = cva("h-fit", {
  variants: {
    variant: {
      default: "",
      link: "underline decoration cursor-pointer",
      h1: "text-xl sm:text-2xl md:text-5xl lg:text-6xl font-semibold mx-1 md:mx-2.5",
      h2: "text-lg sm:text-2xl md:text-3xl lg:text-4xl font-semibold mx-1 md:mx-2",
      h3: "text-base sm:text-lg md:text-xl lg:text-2xl font-medium mx-1 md:mx-5",
      h4: "text-sm sm:text-base md:text-lg lg:text-xl font-medium mx-1 md:mx-1.5",
      h5: "text-xs sm:text-sm md:text-base lg:text-lg font-normal mx-1 md:mx-1.5",
      h6: "text-xs sm:text-xs md:text-sm lg:text-base font-normal mx-1 md:mx-1.5",
      p: "text-sm mx-1 md:mx-1.5",
      small: "text-xs inline-block mx-1 md:mx-1.5",
    },
    weight: {
      regular: "font-regular",
      normal: "font-normal",
      medium: "font-medium",
      semibold: "font-semibold",
      bold: "font-bold",
    },
    align: {
      left: "text-left",
      center: "text-center",
      right: "text-right",
      justify: "text-justify",
    },
    textColor: {
      default: "text-foreground",
      primary: "text-primary",
      secondary: "text-secondary",
      tertiary: "text-tertiary",
      white: "text-white",
      black: "text-black",
      "white-50": "text-white-50",
      "gray-10": "text-gray-10",
      "blue-40": "text-blue-40",
      "gray-60": "text-gray-60",
      "gray-65": "text-gray-65",
      "gray-75": "text-gray-75",
      "gray-85": "text-gray-85",
      "gray-90": "text-gray-90",
      "red-50": "text-red-50",
      "green-10": "text-green-10",
      "green-50": "text-green-50",
      "green-100": "text-green-100",
      "primary-60": "text-primary-60",
      "black-5": "text-black-5",
      "primary-gradient": "text-gradient-to-r from-[#59D8A7] to-[#022C3C]",
    },
    lineHeight: {
      xs: "leading-5",
      sm: "leading-6",
      md: "leading-8",
      lg: "leading-10",
      xl: "leading-12",
      xxl: "leading-14",
      xxxl: "leading-16",
    },
    fontFamily: {
      poppins: "font-poppins",
      spaceMono: "font-space-mono",
    },
  },
  defaultVariants: {
    variant: "default",
  },
});
