import { cva } from "class-variance-authority";

export const textVariants = cva("", {
  variants: {
    variant: {
      default: "",
      link: "underline decoration cursor-pointer",
      // h1: "text-xl sm:text-2xl md:text-5xl lg:text-6xl font-semibold mx-1 md:mx-2.5",
      h1: "text-[36px] leading-[70px] sm:text-[42px] md:text-[48px] lg:text-[60px] font-semibold mx-1.75 md:mx-3",
      // h2: "text-lg sm:text-2xl md:text-3xl lg:text-[40px] font-semibold mx-1 md:mx-2",
      h2: "text-[28px] tracking-[-0.015em] sm:text-[32px] sm:tracking-[-0.015em] md:text-[36px] md:tracking-[-0.02em] lg:text-[40px] lg:tracking-[-0.02em] font-semibold mx-1.5 md:mx-3",
      // h3: "text-base sm:text-lg md:text-xl lg:text-2xl font-medium mx-1 md:mx-1.5",
      h3: "text-[18px] leading-[24px] tracking-[-0.01em] sm:text-[20px] sm:leading-[26px] sm:tracking-[-0.01em] md:text-[22px] md:leading-[28px] md:tracking-[-0.015em] lg:text-[24px] lg:leading-[30px] lg:tracking-[-0.015em] mx-1.5 md:mx-2",
      // h4: "text-sm sm:text-base md:text-lg lg:text-xl font-medium mx-1 md:mx-1.5",
      h4: "text-[16px] leading-[22px] tracking-[-0.005em] sm:text-[17px] sm:leading-[23px] sm:tracking-[-0.005em] md:text-[18px] md:leading-[24px] md:tracking-[-0.01em] lg:text-[20px] lg:leading-[26px] lg:tracking-[-0.01em] mx-1 md:mx-1.5",
      // h5: "text-xs sm:text-sm md:text-base lg:text-lg font-normal mx-1 md:mx-1.5",
      h5: "text-[14px] leading-[20px] tracking-[-0.005em] sm:text-[15px] sm:leading-[21px] sm:tracking-[-0.005em] md:text-[16px] md:leading-[22px] md:tracking-[-0.01em] lg:text-[18px] lg:leading-[24px] lg:tracking-[-0.01em] mx-1 md:mx-1.5",
      // h6: "text-xs sm:text-xs md:text-sm lg:text-base font-normal mx-1 md:mx-1.5",
      h6: "text-[13px] leading-[18px] tracking-[0em] sm:text-[14px] sm:leading-[20px] sm:tracking-[0em] md:text-[15px] md:leading-[21px] md:tracking-[-0.005em] lg:text-[16px] lg:leading-[22px] lg:tracking-[-0.005em] mx-1 md:mx-1.5",
      // p: "text-sm mx-1 md:mx-1.5",
      p: "text-[12px] leading-[16px] tracking-[0em] sm:text-[12px] sm:leading-[18px] sm:tracking-[0em] md:text-[13px] md:leading-[19px] md:tracking-[0em] lg:text-[14px] lg:leading-[20px] lg:tracking-[-0.005em] mx-1 md:mx-1.5",
      // small: "text-xs inline-block mx-1 md:mx-1.5",
      small:
        "block text-[12px] leading-[14px] tracking-[0em] sm:text-[12px] sm:leading-[14px] sm:tracking-[0em] md:text-[12px] md:leading-[14px] md:tracking-[0em] lg:text-[12px] lg:leading-[14px] lg:tracking-[0em] mx-1 md:mx-1.5",
    },
    weight: {
      regular: "font-regular",
      normal: "font-normal",
      medium: "font-medium",
      semibold: "font-semibold",
      bold: "font-bold",
    },
    align: {
      left: "text-left",
      center: "text-center",
      right: "text-right",
      justify: "text-justify",
    },
    textColor: {
      default: "text-foreground",
      primary: "text-primary",
      secondary: "text-secondary",
      tertiary: "text-tertiary",
      white: "text-white",
      black: "text-black",
      "white-50": "text-white-50",
      "gray-10": "text-gray-10",
      "blue-40": "text-blue-40",
      "gray-60": "text-gray-60",
      "gray-65": "text-gray-65",
      "gray-75": "text-gray-75",
      "gray-85": "text-gray-85",
      "gray-90": "text-gray-90",
      "gray-100": "text-gray-100",
      "red-50": "text-red-50",
      "green-10": "text-green-10",
      "green-50": "text-green-50",
      "green-100": "text-green-100",
      "primary-60": "text-primary-60",
      "gray-84": "text-gray-84",
      "black-20": "text-black-20",
      "primary-70": "text-primary-70",
      "gray-80": "text-gray-80",
      "black-15": "text-black-15",
      "gray-106": "text-gray-106",
      "gray-107": "text-gray-107",
      "black-5": "text-black-5",
      "primary-105": "text-primary-105",
      "primary-gradient": "text-gradient-to-r from-[#59D8A7] to-[#022C3C]",
      "orange-50": "text-orange-50",
      "primary-85": "text-primary-85",
      "gray-66": "text-gray-66",
      "primary-170": "text-primary-170",
      "primary-180": "text-primary-180",
      "primary-200": "text-primary-200",
    },
    lineHeight: {
      xs: "leading-5",
      sm: "leading-6",
      md: "leading-8",
      lg: "leading-10",
      xl: "leading-12",
      xxl: "leading-14",
      xxxl: "leading-16",
    },
    fontFamily: {
      poppins: "font-poppins",
      spaceMono: "font-space-mono",
    },
  },
  defaultVariants: {
    variant: "default",
  },
});
