import { cva } from "class-variance-authority";

export const textVariants = cva("", {
  variants: {
    variant: {
      default: "",
      link: "underline decoration cursor-pointer",
      h1: "text-[36px] leading-[44px] sm:text-[42px] md:text-[48px] md:leading-[70px] lg:text-[60px] font-semibold mx-1.75 md:mx-3.75",
      h2: "text-[28px] leading-[36px] sm:text-[32px] md:text-[36px] md:leading-[48px] lg:text-[40px] font-semibold mx-1.5 md:mx-2.25",
      h3: "text-[18px] leading-[24px] sm:text-[20px] md:text-[22px] md:leading-[30px] lg:text-[24px] mx-1.5 md:mx-1.5",
      h4: "text-[16px] leading-[22px] sm:text-[17px] md:text-[18px] md:leading-[26px] lg:text-[20px] mx-1 md:mx-1.25",
      h5: "text-[14px] leading-[20px] sm:text-[15px] md:text-[16px] md:leading-[24px] lg:text-[18px] mx-1 md:mx-1",
      h6: "text-[13px] leading-[18px] sm:text-[14px] md:text-[15px] md:leading-[22px] lg:text-[16px] mx-1 md:mx-1",
      p: " text-[12px] leading-[16px] sm:text-[12px] md:text-[13px] md:leading-[20px] lg:text-[14px] mx-1 md:mx-1",
      small:
        "block text-[12px] leading-[14px] sm:text-[12px] md:text-[12px] lg:text-[12px] mx-1 md:mx-1",
    },
    weight: {
      regular: "font-regular",
      normal: "font-normal",
      medium: "font-medium",
      semibold: "font-semibold",
      bold: "font-bold",
    },
    align: {
      left: "text-left",
      center: "text-center",
      right: "text-right",
      justify: "text-justify",
    },
    textColor: {
      default: "text-black",
      primary: "text-primary",
      "deep-blue": "deep-blue",
      white: "text-white",
      black: "text-black",
      "cloud-gray": "text-cloud-gray",
      "gray-02": "text-gray-02",
      "gray-01": "text-gray-01",
      "gray-65": "text-gray-65",
      "gray-04": "text-gray-04",
      "gray-03": "text-gray-03",
      "gray-05": "text-gray-05",
      "gray-100": "text-gray-100",
      "pulse-red": "text-pulse-red",
      "deep-forest": "text-deep-forest",
      "neev-green": "text-neev-green",
      "primary-90": "text-primary-90",
      "gray-80": "text-gray-80",
      "black/60": "text-black/60",
      "black/82": "text-black/82",
      "white/60": "text-white/60",
      "primary-105": "text-primary-105",
      "primary-gradient": "text-gradient-to-r from-[#59D8A7] to-[#022C3C]",
      yellow: "text-yellow",
      "primary-85": "text-primary-85",
      "primary-230": "text-primary-230/20",
    },
    lineHeight: {
      xs: "leading-5",
      sm: "leading-6",
      md: "leading-8",
      lg: "leading-10",
      xl: "leading-12",
      xxl: "leading-14",
      xxxl: "leading-16",
    },
    fontFamily: {
      poppins: "font-poppins",
      spaceMono: "font-space-mono",
    },
  },
  defaultVariants: {
    variant: "default",
  },
});
