import { cva } from "class-variance-authority";

export const linkVariants = cva(
  "cursor-pointer w-fit disabled:opacity-50 disabled:cursor-not-allowed text-center block",
  {
    variants: {
      variant: {
        default: `bg-primary text-white`,
        secondary: `bg-deep-forest text-white`,
        "deep-blue": `bg-deep-blue`,
        outline: `border border-black text-black`,
        "outline-gray": `border border-gray-03 text-gray-03`,
        black: `bg-black text-white`,
        "outline-primary": `bg-white`,
        white: `bg-white`,
        "white-outline-right": `border-r border-white/12`,
        "white-outline": `border border-white text-white`,
        ghost: `bg-transparent`,
        gray: "bg-cloud-gray",
        link: "decoration cursor-pointer inline",
      },
      size: {
        default: "text-sm",
        sm: "text-sm",
        xs: "text-xs",
        md: "text-md",
        lg: "text-lg",
        xl: "text-xl",
        xxl: "text-2xl",
        full: "w-full",
        none: "text-sm",
      },
      textColor: {
        default: "text-white",
        primary: "text-primary",
        secondary: "text-secondary",
        destructive: "text-destructive",
        outline: "text-cloud-gray",
        blue: "text-gray-02",
        black: "text-black",
        ghost: "text-white/6",
        gray: "text-gray-80",
        "gray-03": "text-gray-03",
        "pulse-red": "text-pulse-red",
      },
      weight: {
        default: "font-normal",
        medium: "font-medium",
        normal: "font-normal",
        semibold: "font-semibold",
        bold: "font-bold",
      },
      spacing: {
        none: "p-0",
        default: "px-3 py-2",
        xs: "px-2 py-1",
        xxs: "px-1 py-0",
        sm: "px-3 py-1.5",
        md: "px-4 py-2",
        lg: "px-8 py-2",
        xl: "px-10 py-3",
      },
      fontFamily: {
        spaceMono: "font-space-mono",
      },
      backgroundColor: {
        default: "bg-white",
        primary: "bg-primary",
        secondary: "bg-secondary",
        destructive: "bg-destructive",
        outline: "bg-white",
        blue: "bg-gray-02",
        ghost: "bg-white/6",
        "cloud-gray": "bg-cloud-gray",
        transparent: "bg-transparent",
      },
      borderRadius: {
        default: "rounded-sm",
        sm: "rounded-sm",
        xs: "rounded-xs",
        lg: "rounded-lg",
        xl: "rounded-xl",
        full: "rounded-full",
        left: "rounded-l-md rounded-r-none",
        right: "rounded-r-md rounded-l-none",
        none: "rounded-none",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
      spacing: "default",
      weight: "medium",
      borderRadius: "default",
    },
  }
);
