import {
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Clock,
  Code2,
  Command,
  Cpu,
  CpuIcon,
  Eye,
  Gauge,
  Gift,
  HardDrive,
  ImageIcon,
  IndianRupee,
  Languages,
  LayoutList,
  LogOut,
  Mail,
  MapPinned,
  MemoryStick,
  Menu,
  MessageSquare,
  Mic,
  MoveLeft,
  MoveRight,
  PenLine,
  Phone,
  Play,
  Search,
  Server,
  Shuffle,
  SquareCheck,
  Star,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type { LucideIcon };

export {
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Clock,
  Code2,
  Command,
  Cpu,
  CpuIcon,
  Eye,
  Gauge,
  Gift,
  HardDrive,
  ImageIcon,
  IndianRupee,
  Languages,
  LayoutList,
  LogOut,
  Mail,
  MapPinned,
  MemoryStick,
  Menu,
  MessageSquare,
  Mic,
  MoveLeft,
  MoveRight,
  PenLine,
  Phone,
  Play,
  Search,
  Server,
  Shuffle,
  SquareCheck,
  Star,
  Zap,
};

export const LUCIDE_ICONS = {
  "arrow-right": ArrowRight,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  clock: Clock,
  "code-2": Code2,
  command: Command,
  cpu: Cpu,
  "cpu-icon": CpuIcon,
  eye: Eye,
  gauge: Gauge,
  gift: Gift,
  "hard-drive": HardDrive,
  "image-icon": ImageIcon,
  "indian-rupee": IndianRupee,
  languages: Languages,
  "layout-list": LayoutList,
  "log-out": LogOut,
  mail: Mail,
  "map-pinned": MapPinned,
  "memory-stick": MemoryStick,
  menu: Menu,
  "message-square": MessageSquare,
  mic: Mic,
  "move-left": MoveLeft,
  "move-right": MoveRight,
  "pen-line": PenLine,
  phone: Phone,
  play: Play,
  search: Search,
  server: Server,
  shuffle: Shuffle,
  "square-check": SquareCheck,
  star: Star,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof LUCIDE_ICONS;

export function resolveLucideIcon(
  icon: LucideIconName | LucideIcon,
): LucideIcon {
  return typeof icon === "string" ? LUCIDE_ICONS[icon] : icon;
}
