import {
  ArrowLeft,
  ArrowRight,
  Bot,
  Brain,
  Calendar,
  Check,
  ChessPawn,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  ClipboardCheck,
  Clock,
  Code2,
  Command,
  Cpu,
  CpuIcon,
  DatabaseIcon,
  Eye,
  FlagTriangleRight,
  FlaskConical,
  FolderOpen,
  Gauge,
  Gift,
  GpuIcon,
  HardDrive,
  ImageIcon,
  IndianRupee,
  Landmark,
  Languages,
  LayoutList,
  LogOut,
  Mail,
  MapPinned,
  MemoryStick,
  Menu,
  MessageSquare,
  Mic,
  Microscope,
  MoveLeft,
  MoveRight,
  Network,
  Pause,
  PenLine,
  Phone,
  Play,
  RadioTower,
  Replace,
  Router,
  ScrollText,
  Search,
  SearchCode,
  Server,
  Shield,
  ShieldCheck,
  Shuffle,
  SquareCheck,
  Star,
  Trophy,
  Users,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type { LucideIcon };

export {
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Clock,
  Code2,
  Command,
  Cpu,
  CpuIcon,
  Eye,
  FlaskConical,
  Gauge,
  Gift,
  HardDrive,
  ImageIcon,
  IndianRupee,
  Languages,
  LayoutList,
  LogOut,
  GpuIcon,
  Mail,
  MapPinned,
  MemoryStick,
  Menu,
  Landmark,
  MessageSquare,
  Mic,
  MoveLeft,
  MoveRight,
  Pause,
  PenLine,
  Phone,
  Play,
  Search,
  Server,
  Shuffle,
  SquareCheck,
  FolderOpen,
  Star,
  Zap,
  Replace,
  FlagTriangleRight,
  Trophy,
  Microscope,
  DatabaseIcon,
  ChessPawn,
  ShieldCheck,
  ArrowLeft,
  Shield,
  Bot,
  SearchCode,
  Brain,
  ScrollText,
  RadioTower,
  Network,
  ClipboardCheck,
  Router,
  Users,
};

export const LUCIDE_ICONS = {
  bot: Bot,
  router: Router,
  network: Network,
  clipboardCheck: ClipboardCheck,
  radioTower: RadioTower,
  scrollText: ScrollText,
  brain: Brain,
  searchCode: SearchCode,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  clock: Clock,
  "code-2": Code2,
  command: Command,
  cpu: Cpu,
  "cpu-icon": CpuIcon,
  eye: Eye,
  gauge: Gauge,
  gift: Gift,
  "hard-drive": HardDrive,
  "image-icon": ImageIcon,
  "indian-rupee": IndianRupee,
  languages: Languages,
  "layout-list": LayoutList,
  "log-out": LogOut,
  mail: Mail,
  "map-pinned": MapPinned,
  "memory-stick": MemoryStick,
  menu: Menu,
  "message-square": MessageSquare,
  mic: Mic,
  "move-left": MoveLeft,
  "move-right": MoveRight,
  "pen-line": PenLine,
  phone: Phone,
  play: Play,
  search: Search,
  server: Server,
  shuffle: Shuffle,
  "square-check": SquareCheck,
  star: Star,
  zap: Zap,
  landmark: Landmark,
  flaskConical: FlaskConical,
  users: Users,
  flagTriangleRight: FlagTriangleRight,
  trophy: Trophy,
  microscope: Microscope,
  chessPawn: ChessPawn,
  protected: ShieldCheck,
  shield: Shield,
  gpuIcon: GpuIcon,
  databaseIcon: DatabaseIcon,
  folderOpen: FolderOpen,
  replace: Replace,
} as const satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof LUCIDE_ICONS;

export function resolveLucideIcon(
  icon: LucideIconName | LucideIcon,
): LucideIcon {
  return typeof icon === "string" ? LUCIDE_ICONS[icon] : icon;
}
